#############################################################################
# Makefile for building: Huen
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  Huen.pro
# Template: app
# Command: /opt/qt5/bin/qmake -o Makefile Huen.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fopenmp -fopenmp -fopenmp -fopenmp -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -fopenmp -fopenmp -fopenmp -fopenmp -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/ImageMagick-6 -I/opt/qt5/include -I/opt/qt5/include/QtWidgets -I/opt/qt5/include/QtGui -I/opt/qt5/include/QtCore -I. -isystem /usr/include/libdrm -I/opt/qt5/mkspecs/linux-g++
QMAKE         = /opt/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Huen1.0.0
DISTDIR = /home/mark/Development/Huen/.tmp/Huen1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lMagick++-6.Q16HDRI -lMagickWand-6.Q16HDRI -lMagickCore-6.Q16HDRI -L/opt/qt5/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		readplasmaconfig.cpp \
		imagergb.cpp \
		writetheme.cpp \
		oneclick.cpp \
		colourops.cpp 
OBJECTS       = main.o \
		readplasmaconfig.o \
		imagergb.o \
		writetheme.o \
		oneclick.o \
		colourops.o
DIST          = /opt/qt5/mkspecs/features/spec_pre.prf \
		/opt/qt5/mkspecs/common/unix.conf \
		/opt/qt5/mkspecs/common/linux.conf \
		/opt/qt5/mkspecs/common/sanitize.conf \
		/opt/qt5/mkspecs/common/gcc-base.conf \
		/opt/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/mkspecs/common/g++-base.conf \
		/opt/qt5/mkspecs/common/g++-unix.conf \
		/opt/qt5/mkspecs/qconfig.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/opt/qt5/mkspecs/features/qt_functions.prf \
		/opt/qt5/mkspecs/features/qt_config.prf \
		/opt/qt5/mkspecs/linux-g++/qmake.conf \
		/opt/qt5/mkspecs/features/spec_post.prf \
		/opt/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/mkspecs/features/toolchain.prf \
		/opt/qt5/mkspecs/features/default_pre.prf \
		/opt/qt5/mkspecs/features/resolve_config.prf \
		/opt/qt5/mkspecs/features/default_post.prf \
		/opt/qt5/mkspecs/features/link_pkgconfig.prf \
		/opt/qt5/mkspecs/features/warn_on.prf \
		/opt/qt5/mkspecs/features/qt.prf \
		/opt/qt5/mkspecs/features/resources.prf \
		/opt/qt5/mkspecs/features/moc.prf \
		/opt/qt5/mkspecs/features/unix/opengl.prf \
		/opt/qt5/mkspecs/features/uic.prf \
		/opt/qt5/mkspecs/features/unix/thread.prf \
		/opt/qt5/mkspecs/features/qmake_use.prf \
		/opt/qt5/mkspecs/features/file_copies.prf \
		/opt/qt5/mkspecs/features/testcase_targets.prf \
		/opt/qt5/mkspecs/features/exceptions.prf \
		/opt/qt5/mkspecs/features/yacc.prf \
		/opt/qt5/mkspecs/features/lex.prf \
		Huen.pro readplasmaconfig.h \
		imagergb.h \
		writetheme.h \
		template.h \
		oneclick.h \
		colourops.h \
		defs.h main.cpp \
		readplasmaconfig.cpp \
		imagergb.cpp \
		writetheme.cpp \
		oneclick.cpp \
		colourops.cpp
QMAKE_TARGET  = Huen
DESTDIR       = 
TARGET        = Huen


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Huen.pro /opt/qt5/mkspecs/linux-g++/qmake.conf /opt/qt5/mkspecs/features/spec_pre.prf \
		/opt/qt5/mkspecs/common/unix.conf \
		/opt/qt5/mkspecs/common/linux.conf \
		/opt/qt5/mkspecs/common/sanitize.conf \
		/opt/qt5/mkspecs/common/gcc-base.conf \
		/opt/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/mkspecs/common/g++-base.conf \
		/opt/qt5/mkspecs/common/g++-unix.conf \
		/opt/qt5/mkspecs/qconfig.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/opt/qt5/mkspecs/features/qt_functions.prf \
		/opt/qt5/mkspecs/features/qt_config.prf \
		/opt/qt5/mkspecs/linux-g++/qmake.conf \
		/opt/qt5/mkspecs/features/spec_post.prf \
		/opt/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/mkspecs/features/toolchain.prf \
		/opt/qt5/mkspecs/features/default_pre.prf \
		/opt/qt5/mkspecs/features/resolve_config.prf \
		/opt/qt5/mkspecs/features/default_post.prf \
		/opt/qt5/mkspecs/features/link_pkgconfig.prf \
		/opt/qt5/mkspecs/features/warn_on.prf \
		/opt/qt5/mkspecs/features/qt.prf \
		/opt/qt5/mkspecs/features/resources.prf \
		/opt/qt5/mkspecs/features/moc.prf \
		/opt/qt5/mkspecs/features/unix/opengl.prf \
		/opt/qt5/mkspecs/features/uic.prf \
		/opt/qt5/mkspecs/features/unix/thread.prf \
		/opt/qt5/mkspecs/features/qmake_use.prf \
		/opt/qt5/mkspecs/features/file_copies.prf \
		/opt/qt5/mkspecs/features/testcase_targets.prf \
		/opt/qt5/mkspecs/features/exceptions.prf \
		/opt/qt5/mkspecs/features/yacc.prf \
		/opt/qt5/mkspecs/features/lex.prf \
		Huen.pro \
		/opt/qt5/lib/libQt5Widgets.prl \
		/opt/qt5/lib/libQt5Gui.prl \
		/opt/qt5/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Huen.pro
/opt/qt5/mkspecs/features/spec_pre.prf:
/opt/qt5/mkspecs/common/unix.conf:
/opt/qt5/mkspecs/common/linux.conf:
/opt/qt5/mkspecs/common/sanitize.conf:
/opt/qt5/mkspecs/common/gcc-base.conf:
/opt/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/qt5/mkspecs/common/g++-base.conf:
/opt/qt5/mkspecs/common/g++-unix.conf:
/opt/qt5/mkspecs/qconfig.pri:
/opt/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/opt/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_3drender.pri:
/opt/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_charts.pri:
/opt/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/opt/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_location.pri:
/opt/qt5/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/opt/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_purchasing.pri:
/opt/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_repparser.pri:
/opt/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/opt/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webkit.pri:
/opt/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webview.pri:
/opt/qt5/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/opt/qt5/mkspecs/features/qt_functions.prf:
/opt/qt5/mkspecs/features/qt_config.prf:
/opt/qt5/mkspecs/linux-g++/qmake.conf:
/opt/qt5/mkspecs/features/spec_post.prf:
/opt/qt5/mkspecs/features/exclusive_builds.prf:
/opt/qt5/mkspecs/features/toolchain.prf:
/opt/qt5/mkspecs/features/default_pre.prf:
/opt/qt5/mkspecs/features/resolve_config.prf:
/opt/qt5/mkspecs/features/default_post.prf:
/opt/qt5/mkspecs/features/link_pkgconfig.prf:
/opt/qt5/mkspecs/features/warn_on.prf:
/opt/qt5/mkspecs/features/qt.prf:
/opt/qt5/mkspecs/features/resources.prf:
/opt/qt5/mkspecs/features/moc.prf:
/opt/qt5/mkspecs/features/unix/opengl.prf:
/opt/qt5/mkspecs/features/uic.prf:
/opt/qt5/mkspecs/features/unix/thread.prf:
/opt/qt5/mkspecs/features/qmake_use.prf:
/opt/qt5/mkspecs/features/file_copies.prf:
/opt/qt5/mkspecs/features/testcase_targets.prf:
/opt/qt5/mkspecs/features/exceptions.prf:
/opt/qt5/mkspecs/features/yacc.prf:
/opt/qt5/mkspecs/features/lex.prf:
Huen.pro:
/opt/qt5/lib/libQt5Widgets.prl:
/opt/qt5/lib/libQt5Gui.prl:
/opt/qt5/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Huen.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents readplasmaconfig.h imagergb.h writetheme.h template.h oneclick.h colourops.h defs.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp readplasmaconfig.cpp imagergb.cpp writetheme.cpp oneclick.cpp colourops.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -fopenmp -fopenmp -fopenmp -fopenmp -Wall -W -dM -E -o moc_predefs.h /opt/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp oneclick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

readplasmaconfig.o: readplasmaconfig.cpp /opt/qt5/include/QtCore/QFile \
		/opt/qt5/include/QtCore/qfile.h \
		/opt/qt5/include/QtCore/qfiledevice.h \
		/opt/qt5/include/QtCore/qiodevice.h \
		/opt/qt5/include/QtCore/qglobal.h \
		/opt/qt5/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5/include/QtCore/qconfig.h \
		/opt/qt5/include/QtCore/qtcore-config.h \
		/opt/qt5/include/QtCore/qsystemdetection.h \
		/opt/qt5/include/QtCore/qprocessordetection.h \
		/opt/qt5/include/QtCore/qcompilerdetection.h \
		/opt/qt5/include/QtCore/qtypeinfo.h \
		/opt/qt5/include/QtCore/qsysinfo.h \
		/opt/qt5/include/QtCore/qlogging.h \
		/opt/qt5/include/QtCore/qflags.h \
		/opt/qt5/include/QtCore/qatomic.h \
		/opt/qt5/include/QtCore/qbasicatomic.h \
		/opt/qt5/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/include/QtCore/qgenericatomic.h \
		/opt/qt5/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/include/QtCore/qatomic_msvc.h \
		/opt/qt5/include/QtCore/qglobalstatic.h \
		/opt/qt5/include/QtCore/qmutex.h \
		/opt/qt5/include/QtCore/qnumeric.h \
		/opt/qt5/include/QtCore/qversiontagging.h \
		/opt/qt5/include/QtCore/qobject.h \
		/opt/qt5/include/QtCore/qobjectdefs.h \
		/opt/qt5/include/QtCore/qnamespace.h \
		/opt/qt5/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/include/QtCore/qstring.h \
		/opt/qt5/include/QtCore/qchar.h \
		/opt/qt5/include/QtCore/qbytearray.h \
		/opt/qt5/include/QtCore/qrefcount.h \
		/opt/qt5/include/QtCore/qarraydata.h \
		/opt/qt5/include/QtCore/qstringbuilder.h \
		/opt/qt5/include/QtCore/qlist.h \
		/opt/qt5/include/QtCore/qalgorithms.h \
		/opt/qt5/include/QtCore/qiterator.h \
		/opt/qt5/include/QtCore/qhashfunctions.h \
		/opt/qt5/include/QtCore/qpair.h \
		/opt/qt5/include/QtCore/qbytearraylist.h \
		/opt/qt5/include/QtCore/qstringlist.h \
		/opt/qt5/include/QtCore/qregexp.h \
		/opt/qt5/include/QtCore/qstringmatcher.h \
		/opt/qt5/include/QtCore/qcoreevent.h \
		/opt/qt5/include/QtCore/qscopedpointer.h \
		/opt/qt5/include/QtCore/qmetatype.h \
		/opt/qt5/include/QtCore/qvarlengtharray.h \
		/opt/qt5/include/QtCore/qcontainerfwd.h \
		/opt/qt5/include/QtCore/qobject_impl.h \
		/opt/qt5/include/QtCore/QString \
		/opt/qt5/include/QtCore/QStandardPaths \
		/opt/qt5/include/QtCore/qstandardpaths.h \
		/opt/qt5/include/QtCore/QTextStream \
		/opt/qt5/include/QtCore/qtextstream.h \
		/opt/qt5/include/QtCore/qlocale.h \
		/opt/qt5/include/QtCore/qvariant.h \
		/opt/qt5/include/QtCore/qmap.h \
		/opt/qt5/include/QtCore/qdebug.h \
		/opt/qt5/include/QtCore/qhash.h \
		/opt/qt5/include/QtCore/qvector.h \
		/opt/qt5/include/QtCore/qpoint.h \
		/opt/qt5/include/QtCore/qset.h \
		/opt/qt5/include/QtCore/qcontiguouscache.h \
		/opt/qt5/include/QtCore/qsharedpointer.h \
		/opt/qt5/include/QtCore/qshareddata.h \
		/opt/qt5/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/include/QtCore/QDebug \
		readplasmaconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readplasmaconfig.o readplasmaconfig.cpp

imagergb.o: imagergb.cpp /opt/qt5/include/QtCore/QString \
		/opt/qt5/include/QtCore/qstring.h \
		/opt/qt5/include/QtCore/qchar.h \
		/opt/qt5/include/QtCore/qglobal.h \
		/opt/qt5/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5/include/QtCore/qconfig.h \
		/opt/qt5/include/QtCore/qtcore-config.h \
		/opt/qt5/include/QtCore/qsystemdetection.h \
		/opt/qt5/include/QtCore/qprocessordetection.h \
		/opt/qt5/include/QtCore/qcompilerdetection.h \
		/opt/qt5/include/QtCore/qtypeinfo.h \
		/opt/qt5/include/QtCore/qsysinfo.h \
		/opt/qt5/include/QtCore/qlogging.h \
		/opt/qt5/include/QtCore/qflags.h \
		/opt/qt5/include/QtCore/qatomic.h \
		/opt/qt5/include/QtCore/qbasicatomic.h \
		/opt/qt5/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/include/QtCore/qgenericatomic.h \
		/opt/qt5/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/include/QtCore/qatomic_msvc.h \
		/opt/qt5/include/QtCore/qglobalstatic.h \
		/opt/qt5/include/QtCore/qmutex.h \
		/opt/qt5/include/QtCore/qnumeric.h \
		/opt/qt5/include/QtCore/qversiontagging.h \
		/opt/qt5/include/QtCore/qbytearray.h \
		/opt/qt5/include/QtCore/qrefcount.h \
		/opt/qt5/include/QtCore/qnamespace.h \
		/opt/qt5/include/QtCore/qarraydata.h \
		/opt/qt5/include/QtCore/qstringbuilder.h \
		imagergb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagergb.o imagergb.cpp

writetheme.o: writetheme.cpp /opt/qt5/include/QtCore/QString \
		/opt/qt5/include/QtCore/qstring.h \
		/opt/qt5/include/QtCore/qchar.h \
		/opt/qt5/include/QtCore/qglobal.h \
		/opt/qt5/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5/include/QtCore/qconfig.h \
		/opt/qt5/include/QtCore/qtcore-config.h \
		/opt/qt5/include/QtCore/qsystemdetection.h \
		/opt/qt5/include/QtCore/qprocessordetection.h \
		/opt/qt5/include/QtCore/qcompilerdetection.h \
		/opt/qt5/include/QtCore/qtypeinfo.h \
		/opt/qt5/include/QtCore/qsysinfo.h \
		/opt/qt5/include/QtCore/qlogging.h \
		/opt/qt5/include/QtCore/qflags.h \
		/opt/qt5/include/QtCore/qatomic.h \
		/opt/qt5/include/QtCore/qbasicatomic.h \
		/opt/qt5/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/include/QtCore/qgenericatomic.h \
		/opt/qt5/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/include/QtCore/qatomic_msvc.h \
		/opt/qt5/include/QtCore/qglobalstatic.h \
		/opt/qt5/include/QtCore/qmutex.h \
		/opt/qt5/include/QtCore/qnumeric.h \
		/opt/qt5/include/QtCore/qversiontagging.h \
		/opt/qt5/include/QtCore/qbytearray.h \
		/opt/qt5/include/QtCore/qrefcount.h \
		/opt/qt5/include/QtCore/qnamespace.h \
		/opt/qt5/include/QtCore/qarraydata.h \
		/opt/qt5/include/QtCore/qstringbuilder.h \
		/opt/qt5/include/QtCore/QFile \
		/opt/qt5/include/QtCore/qfile.h \
		/opt/qt5/include/QtCore/qfiledevice.h \
		/opt/qt5/include/QtCore/qiodevice.h \
		/opt/qt5/include/QtCore/qobject.h \
		/opt/qt5/include/QtCore/qobjectdefs.h \
		/opt/qt5/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/include/QtCore/qlist.h \
		/opt/qt5/include/QtCore/qalgorithms.h \
		/opt/qt5/include/QtCore/qiterator.h \
		/opt/qt5/include/QtCore/qhashfunctions.h \
		/opt/qt5/include/QtCore/qpair.h \
		/opt/qt5/include/QtCore/qbytearraylist.h \
		/opt/qt5/include/QtCore/qstringlist.h \
		/opt/qt5/include/QtCore/qregexp.h \
		/opt/qt5/include/QtCore/qstringmatcher.h \
		/opt/qt5/include/QtCore/qcoreevent.h \
		/opt/qt5/include/QtCore/qscopedpointer.h \
		/opt/qt5/include/QtCore/qmetatype.h \
		/opt/qt5/include/QtCore/qvarlengtharray.h \
		/opt/qt5/include/QtCore/qcontainerfwd.h \
		/opt/qt5/include/QtCore/qobject_impl.h \
		/opt/qt5/include/QtCore/QTextStream \
		/opt/qt5/include/QtCore/qtextstream.h \
		/opt/qt5/include/QtCore/qlocale.h \
		/opt/qt5/include/QtCore/qvariant.h \
		/opt/qt5/include/QtCore/qmap.h \
		/opt/qt5/include/QtCore/qdebug.h \
		/opt/qt5/include/QtCore/qhash.h \
		/opt/qt5/include/QtCore/qvector.h \
		/opt/qt5/include/QtCore/qpoint.h \
		/opt/qt5/include/QtCore/qset.h \
		/opt/qt5/include/QtCore/qcontiguouscache.h \
		/opt/qt5/include/QtCore/qsharedpointer.h \
		/opt/qt5/include/QtCore/qshareddata.h \
		/opt/qt5/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/include/QtCore/QStandardPaths \
		/opt/qt5/include/QtCore/qstandardpaths.h \
		/opt/qt5/include/QtCore/QDir \
		/opt/qt5/include/QtCore/qdir.h \
		/opt/qt5/include/QtCore/qfileinfo.h \
		writetheme.h \
		template.h \
		colourops.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o writetheme.o writetheme.cpp

oneclick.o: oneclick.cpp /opt/qt5/include/QtCore/QDir \
		/opt/qt5/include/QtCore/qdir.h \
		/opt/qt5/include/QtCore/qstring.h \
		/opt/qt5/include/QtCore/qchar.h \
		/opt/qt5/include/QtCore/qglobal.h \
		/opt/qt5/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5/include/QtCore/qconfig.h \
		/opt/qt5/include/QtCore/qtcore-config.h \
		/opt/qt5/include/QtCore/qsystemdetection.h \
		/opt/qt5/include/QtCore/qprocessordetection.h \
		/opt/qt5/include/QtCore/qcompilerdetection.h \
		/opt/qt5/include/QtCore/qtypeinfo.h \
		/opt/qt5/include/QtCore/qsysinfo.h \
		/opt/qt5/include/QtCore/qlogging.h \
		/opt/qt5/include/QtCore/qflags.h \
		/opt/qt5/include/QtCore/qatomic.h \
		/opt/qt5/include/QtCore/qbasicatomic.h \
		/opt/qt5/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/include/QtCore/qgenericatomic.h \
		/opt/qt5/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/include/QtCore/qatomic_msvc.h \
		/opt/qt5/include/QtCore/qglobalstatic.h \
		/opt/qt5/include/QtCore/qmutex.h \
		/opt/qt5/include/QtCore/qnumeric.h \
		/opt/qt5/include/QtCore/qversiontagging.h \
		/opt/qt5/include/QtCore/qbytearray.h \
		/opt/qt5/include/QtCore/qrefcount.h \
		/opt/qt5/include/QtCore/qnamespace.h \
		/opt/qt5/include/QtCore/qarraydata.h \
		/opt/qt5/include/QtCore/qstringbuilder.h \
		/opt/qt5/include/QtCore/qfileinfo.h \
		/opt/qt5/include/QtCore/qfile.h \
		/opt/qt5/include/QtCore/qfiledevice.h \
		/opt/qt5/include/QtCore/qiodevice.h \
		/opt/qt5/include/QtCore/qobject.h \
		/opt/qt5/include/QtCore/qobjectdefs.h \
		/opt/qt5/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/include/QtCore/qlist.h \
		/opt/qt5/include/QtCore/qalgorithms.h \
		/opt/qt5/include/QtCore/qiterator.h \
		/opt/qt5/include/QtCore/qhashfunctions.h \
		/opt/qt5/include/QtCore/qpair.h \
		/opt/qt5/include/QtCore/qbytearraylist.h \
		/opt/qt5/include/QtCore/qstringlist.h \
		/opt/qt5/include/QtCore/qregexp.h \
		/opt/qt5/include/QtCore/qstringmatcher.h \
		/opt/qt5/include/QtCore/qcoreevent.h \
		/opt/qt5/include/QtCore/qscopedpointer.h \
		/opt/qt5/include/QtCore/qmetatype.h \
		/opt/qt5/include/QtCore/qvarlengtharray.h \
		/opt/qt5/include/QtCore/qcontainerfwd.h \
		/opt/qt5/include/QtCore/qobject_impl.h \
		/opt/qt5/include/QtCore/qshareddata.h \
		/opt/qt5/include/QtCore/qhash.h \
		oneclick.h \
		readplasmaconfig.h \
		/opt/qt5/include/QtCore/QString \
		imagergb.h \
		writetheme.h \
		/opt/qt5/include/QtCore/QFile \
		/opt/qt5/include/QtCore/QTextStream \
		/opt/qt5/include/QtCore/qtextstream.h \
		/opt/qt5/include/QtCore/qlocale.h \
		/opt/qt5/include/QtCore/qvariant.h \
		/opt/qt5/include/QtCore/qmap.h \
		/opt/qt5/include/QtCore/qdebug.h \
		/opt/qt5/include/QtCore/qvector.h \
		/opt/qt5/include/QtCore/qpoint.h \
		/opt/qt5/include/QtCore/qset.h \
		/opt/qt5/include/QtCore/qcontiguouscache.h \
		/opt/qt5/include/QtCore/qsharedpointer.h \
		/opt/qt5/include/QtCore/qsharedpointer_impl.h \
		colourops.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oneclick.o oneclick.cpp

colourops.o: colourops.cpp colourops.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colourops.o colourops.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

